version: '3.8'

services:
    db:
      image: postgres:14.1-alpine
      container_name: postgres_db
      environment:
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5432:5432"

    api:
      build:
        context: .
      container_name: api
      command: bundler exec rails server -b 0.0.0.0
      tty: true
      volumes:
        - .:/ZSSN
      ports:
        - "3000:3000"
      depends_on:
        - db